version: '3.9'
services:
  postgres:
    image: postgres:14.7
    restart: always
    environment:
      POSTGRES_USER: databaseuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fiftyonepercent_database
    ports:
      - '5438:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
